package com.samplespace.hellodrlworld;

import com.samplespace.hellodrlworld.PaymentOffers;
import com.samplespace.hellopojoworld.Customer;


rule "Offer for ApplePay"
    ruleflow-group "hello2DRLworld"
	when
		offer: PaymentOffers(channel == "ApplePay")
	then
		offer.setDiscount(15);

	end
	
	
rule "Offer for SamsungPay"
    ruleflow-group "hello2DRLworld"
	when
		offer: PaymentOffers(channel == "SamsungPay")
	then
		offer.setDiscount(20);
	end

	
rule "Offer for GooglePay"
    ruleflow-group "hello2DRLworld"
	when
		offer: PaymentOffers(channel == "GooglePay")
	then
		offer.setDiscount(25);
	end

