package com.samplespace.hellodrlworld;

import com.samplespace.hellodrlworld.PaymentOffers;
import com.samplespace.hellopojoworld01.Customer01;


rule "Offer for ApplePay"
    ruleflow-group "hello2DRLworld"
	when
		offer: PaymentOffers(channel == "ApplePay")
		cust: Customer01()
	then
        cust.setCustName("JD1");
		offer.setDiscount(15);
	end
	
	
rule "Offer for SamsungPay"
    ruleflow-group "hello2DRLworld"
	when
		offer: PaymentOffers(channel == "SamsungPay")
	then
		offer.setDiscount(20);
	end

	
rule "Offer for GooglePay"
    ruleflow-group "hello2DRLworld"
	when
		offer: PaymentOffers(channel == "GooglePay")
	then
		offer.setDiscount(25);
	end

