package com.samplespace.hellodrlworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class payDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String channel;
	private int discount;

	public payDetails() {
	}

	public java.lang.String getChannel() {
		return this.channel;
	}

	public void setChannel(java.lang.String channel) {
		this.channel = channel;
	}

	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	public payDetails(java.lang.String channel, int discount) {
		this.channel = channel;
		this.discount = discount;
	}

}