package com.samplespace.hellodrlworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class payDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public payDetails() {
    }




}