package com.samplespace.hellodrlworld;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentOffers implements java.io.Serializable {

    //static final long serialVersionUID = 1L;

	private String channel;
	private int discount;
	
	public String getChannel() {
		return channel;
	}
	public void setChannel(String channel) {
		this.channel = channel;
	}
	
	public int getDiscount() {
		return discount;
	}
	public void setDiscount(int discount) {
		this.discount = discount;
	}

    public PaymentOffers() {
    }




}